micronaut:
  heartbeat:
    enabled: true
  metrics:
    enabled: ${METRICS_ENABLED:True}
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  server:
    port: ${APPLICATION_SERVER_PORT:7080}
  application:
    name: "webrtc-observer"
#  ssl:
#    enabled: true
#    buildSelfSigned: true
---
endpoints:
  all:
    port: ${APPLICATION_MANAGEMENT_PORT:7081}
  prometheus:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
---
kafka:
  bootstrap:
    servers: ${KAFKA_HOSTS:`localhost:9092`}
---
observer:
  userMediaErrorsMonitor:
    periodInS: 300
  connectors:
    - name: "ReportSinkLogger"
      transformations:
        - type: Filter
          config:
            serviceUUIDs:
              including:
                - "86ed98c6-b001-48bb-b31e-da638b979c72"
      sink:
        type: LoggerSink
        config:
          printReports: False
  hazelcast:
    configFile: ${HAZELCAST_CONFIG_FILE:`classpath:hazelcast.yaml`}
  evaluators:
    pcObserver:
      peerConnectionMaxIdleTimeInS: 300
      mediaStreamUpdatesFlushInS: 15
      mediaStreamsBufferNums: 0
    conurrentStreams:
      enabled: true
      threshold: 100
  outboundReports:
    reportOutboundRTPs: True
    reportInboundRTPs: True
    reportRemoteInboundRTPs: True
    reportTracks: True
    reportMediaSources: True
    reportCandidatePairs: True
    reportLocalCandidates: True
    reportRemoteCandidates: True
    reportUserMediaErrors: True

